# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: budget
      POSTGRES_USER: budget
  api:
     ports:
      - "10000:10000"
     build:
        context: ../
        dockerfile: Dockerfile